
# =========================================================================
SET (PROJECT_VERSION_MAJOR "0")
SET (PROJECT_VERSION_MINOR "1")
SET (PROJECT_VERSION_PATCH "0")
# ----------------------------
## 
set(CPACK_PACKAGE_NAME "libode")
## message("CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")

SET (CPACK_SOURCE_IGNORE_FILES build/*,./.kdev4,.git/*,.gitignore )
SET (CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
## 
SET (CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
SET (CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README.md")

# NEW
SET (CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set (CPACK_DEBIAN_PACKAGE_DEPENDS "")
 
IF (UNIX)
SET (CPACK_SOURCE_GENERATOR "TGZ;ZIP")
SET (CPACK_GENERATOR "TGZ;TBZ2")
ELSE (UNIX)
SET (CPACK_SOURCE_GENERATOR "ZIP")
SET (CPACK_GENERATOR "NSIS")
ENDIF (UNIX)
 
# build a CPack driven installer package
SET (CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
SET (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Description of ODE library")
SET (CPACK_PACKAGE_VENDOR "opherden")
SET (CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
SET (CPACK_PACKAGE_VENDOR "Team")
SET (CPACK_PACKAGE_CONTACT "Knut Opherden <knut.opherden@hotmail.com>")
SET (CPACK_PACKAGE_SECTION "library")
 
SET (CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
SET (CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
SET (CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

# include(Installing)

# =========================================================================

